[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express", "socket.io"]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000

[[headers]]
  for = "/socket.io/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*" 